<a href="https://colab.research.google.com/github/PochampellyDeekshitha/MachineLearning/blob/main/MachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas Exercise-01**

9th question

In [1]:
import pandas as pd
sales_data = {
    2014: [100.5, 150.8, 200.9, 30000, 40000],
    2015: [12000, 18000, 22000, 30000, 45000],
    2016: [20000, 50000, 70000, 100000, 125000],
    2017: [50000, 60000, 70000, 80000, 90000]
}
sales= pd.DataFrame(sales_data, index=['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'])
display(sales)

2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000

10th question

In [2]:
sales.index

Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')

In [3]:
sales.columns

Index([2014, 2015, 2016, 2017], dtype='int64')

In [4]:
sales.shape

(5, 4)

In [5]:
sales.size

20

In [6]:
sales.ndim

2

In [7]:
print(sales.values)

[[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]


In [8]:
sales.tail(2)

2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000

In [9]:
sales.head(2)

2014   2015   2016   2017
Madhu  100.5  12000  20000  50000
Kusum  150.8  18000  50000  60000

In [10]:
dict={2018:[160000,110000,500000,340000,900000]}
sales2=pd.DataFrame(dict,index=['Madhu','kusum','kinshuk','ankith','shruthi'])
print(sales2)

           2018
Madhu    160000
kusum    110000
kinshuk  500000
ankith   340000
shruthi  900000


In [11]:
sales2.empty

False

11th Question

In [12]:
sales=pd.concat([sales,sales2],axis=1)
print(sales)

            2014     2015      2016     2017      2018
Madhu      100.5  12000.0   20000.0  50000.0  160000.0
Kusum      150.8  18000.0   50000.0  60000.0       NaN
Kinshuk    200.9  22000.0   70000.0  70000.0       NaN
Ankit    30000.0  30000.0  100000.0  80000.0       NaN
Shruti   40000.0  45000.0  125000.0  90000.0       NaN
kusum        NaN      NaN       NaN      NaN  110000.0
kinshuk      NaN      NaN       NaN      NaN  500000.0
ankith       NaN      NaN       NaN      NaN  340000.0
shruthi      NaN      NaN       NaN      NaN  900000.0


In [13]:
del sales[2018]

In [14]:
sales=sales.T
print(sales)

        Madhu    Kusum  Kinshuk     Ankit    Shruti  kusum  kinshuk  ankith  \
2014    100.5    150.8    200.9   30000.0   40000.0    NaN      NaN     NaN   
2015  12000.0  18000.0  22000.0   30000.0   45000.0    NaN      NaN     NaN   
2016  20000.0  50000.0  70000.0  100000.0  125000.0    NaN      NaN     NaN   
2017  50000.0  60000.0  70000.0   80000.0   90000.0    NaN      NaN     NaN   

      shruthi  
2014      NaN  
2015      NaN  
2016      NaN  
2017      NaN  


In [16]:
print(sales.loc[2017])

Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
kusum          NaN
kinshuk        NaN
ankith         NaN
shruthi        NaN
Name: 2017, dtype: float64


In [18]:
display(sales.loc[[2017], ['Madhu', 'Ankit']])

Madhu    Ankit
2017  50000.0  80000.0

In [20]:
display(sales.loc[[2016], ['Shruti']])

Shruti
2016  125000.0

In [21]:
print(sales)

        Madhu    Kusum  Kinshuk     Ankit    Shruti  kusum  kinshuk  ankith  \
2014    100.5    150.8    200.9   30000.0   40000.0    NaN      NaN     NaN   
2015  12000.0  18000.0  22000.0   30000.0   45000.0    NaN      NaN     NaN   
2016  20000.0  50000.0  70000.0  100000.0  125000.0    NaN      NaN     NaN   
2017  50000.0  60000.0  70000.0   80000.0   90000.0    NaN      NaN     NaN   

      shruthi  
2014      NaN  
2015      NaN  
2016      NaN  
2017      NaN  


In [23]:
sales.loc['Sumeet'] = [196.2, 37800, 52000, 78438, 38852, 0, 0, 0, 0]
print(sales)

          Madhu    Kusum  Kinshuk     Ankit    Shruti  kusum  kinshuk  ankith  \
2014      100.5    150.8    200.9   30000.0   40000.0    NaN      NaN     NaN   
2015    12000.0  18000.0  22000.0   30000.0   45000.0    NaN      NaN     NaN   
2016    20000.0  50000.0  70000.0  100000.0  125000.0    NaN      NaN     NaN   
2017    50000.0  60000.0  70000.0   80000.0   90000.0    NaN      NaN     NaN   
Sumeet    196.2  37800.0  52000.0   78438.0   38852.0    0.0      0.0     0.0   

        shruthi  
2014        NaN  
2015        NaN  
2016        NaN  
2017        NaN  
Sumeet      0.0  


In [25]:
sales.drop(2014, axis=0, inplace=True)
print(sales)

          Madhu    Kusum  Kinshuk     Ankit    Shruti  kusum  kinshuk  ankith  \
2015    12000.0  18000.0  22000.0   30000.0   45000.0    NaN      NaN     NaN   
2016    20000.0  50000.0  70000.0  100000.0  125000.0    NaN      NaN     NaN   
2017    50000.0  60000.0  70000.0   80000.0   90000.0    NaN      NaN     NaN   
Sumeet    196.2  37800.0  52000.0   78438.0   38852.0    0.0      0.0     0.0   

        shruthi  
2015        NaN  
2016        NaN  
2017        NaN  
Sumeet      0.0  


In [29]:
sales.drop('Kinshuk', axis=1, inplace=True)
print(sales)

          Madhu    Kusum     Ankit    Shruti  kusum  kinshuk  ankith  shruthi
2015    12000.0  18000.0   30000.0   45000.0    NaN      NaN     NaN      NaN
2016    20000.0  50000.0  100000.0  125000.0    NaN      NaN     NaN      NaN
2017    50000.0  60000.0   80000.0   90000.0    NaN      NaN     NaN      NaN
Sumeet    196.2  37800.0   78438.0   38852.0    0.0      0.0     0.0      0.0


In [35]:
sales.rename(index={'Madhu':'shailesh','ankith':'vivaan'},inplace=True)
print(sales)

          shailesh    Kusum    vivaan    Shruti  kusum  kinshuk  ankith  \
2015       12000.0  18000.0   30000.0   45000.0    NaN      NaN     NaN   
2016       20000.0  50000.0  100000.0  125000.0    NaN      NaN     NaN   
2017       50000.0  60000.0   80000.0   90000.0    NaN      NaN     NaN   
Sumeet       196.2  37800.0   78438.0   38852.0    0.0      0.0     0.0   
shailesh       NaN      NaN       NaN       NaN    NaN      NaN     NaN   

          shruthi       2018  
2015          NaN        NaN  
2016          NaN        NaN  
2017          NaN        NaN  
Sumeet        0.0        NaN  
shailesh      NaN  1000000.0  


In [31]:
sales.loc['shailesh',2018]=1000000
print(sales)

            Madhu    Kusum     Ankit    Shruti  kusum  kinshuk  ankith  \
2015      12000.0  18000.0   30000.0   45000.0    NaN      NaN     NaN   
2016      20000.0  50000.0  100000.0  125000.0    NaN      NaN     NaN   
2017      50000.0  60000.0   80000.0   90000.0    NaN      NaN     NaN   
Sumeet      196.2  37800.0   78438.0   38852.0    0.0      0.0     0.0   
shailesh      NaN      NaN       NaN       NaN    NaN      NaN     NaN   

          shruthi       2018  
2015          NaN        NaN  
2016          NaN        NaN  
2017          NaN        NaN  
Sumeet        0.0        NaN  
shailesh      NaN  1000000.0  


In [32]:
sales.to_csv('SalesFigures.csv', index=False, header=False)

In [33]:
SalesRetrieved = pd.read_csv('SalesFigures.csv', header=None)
SalesRetrieved.index = sales.index
SalesRetrieved.columns = sales.columns
print(SalesRetrieved)

            Madhu    Kusum     Ankit    Shruti  kusum  kinshuk  ankith  \
2015      12000.0  18000.0   30000.0   45000.0    NaN      NaN     NaN   
2016      20000.0  50000.0  100000.0  125000.0    NaN      NaN     NaN   
2017      50000.0  60000.0   80000.0   90000.0    NaN      NaN     NaN   
Sumeet      196.2  37800.0   78438.0   38852.0    0.0      0.0     0.0   
shailesh      NaN      NaN       NaN       NaN    NaN      NaN     NaN   

          shruthi       2018  
2015          NaN        NaN  
2016          NaN        NaN  
2017          NaN        NaN  
Sumeet        0.0        NaN  
shailesh      NaN  1000000.0  


**Pandas Exrecise-02**

13th question

In [36]:
import pandas as pd
data = {"Item": ["TV", "TV", "TV", "AC"],"Company": ["LG", "VIDEOCON", "LG", "SONY"],"Rupees": [12000, 10000, 15000, 14000],"USD": [700,650,800,750]}
df = pd.DataFrame(data)
print(df)

  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750


In [38]:
new_data = pd.DataFrame([
{"Item": "TV", "Company": "SAMSUNG", "Rupees": 13000, "USD": 670},
{"Item": "AC", "Company": "Apple", "Rupees": 16000, "USD": 900}
])
df = pd.concat([df, new_data], ignore_index=True)
print(df)


  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
4   TV      SONY   13000  720
5   AC        LG   16000  850
6   TV   SAMSUNG   13000  670
7   AC     Apple   16000  900


In [39]:
lg_tv_max = df[(df['Item'] == 'TV') & (df['Company'] == 'LG')]['Rupees'].max()
print("Maximum price of LG TV:", lg_tv_max)

Maximum price of LG TV: 15000


In [40]:
total_rupees = df['Rupees'].sum()
print("Total sum of all products in Rupees:", total_rupees)

Total sum of all products in Rupees: 109000


In [41]:
sony_median_usd = df[df['Company'] == 'SONY']['USD'].median()
print("Median USD for SONY products:", sony_median_usd)

Median USD for SONY products: 735.0


In [42]:
sorted_df = df.sort_values(by='Rupees')
print(sorted_df)

  Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
6   TV   SAMSUNG   13000  670
4   TV      SONY   13000  720
3   AC      SONY   14000  750
2   TV        LG   15000  800
5   AC        LG   16000  850
7   AC     Apple   16000  900


In [43]:
sorted_df = df.sort_values(by='Rupees')
print(sorted_df)


  Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
6   TV   SAMSUNG   13000  670
4   TV      SONY   13000  720
3   AC      SONY   14000  750
2   TV        LG   15000  800
5   AC        LG   16000  850
7   AC     Apple   16000  900


14th question

In [46]:
import numpy as np
data = {"Name": ["Aparna", "Pankaj", "Ram", "Ramesh", "Naveen", "Krrishnav", "Bhawna"],"Degree": ["MBA", "BCA", "M.Tech", "MBA", "NaN","BCA","MBA"],"Score":[90.0,"NaN",80.0,98.0,97.0,78.0,89.0]}
df2 = pd.DataFrame(data)
print(df2)


        Name  Degree Score
0     Aparna     MBA  90.0
1     Pankaj     BCA   NaN
2        Ram  M.Tech  80.0
3     Ramesh     MBA  98.0
4     Naveen     NaN  97.0
5  Krrishnav     BCA  78.0
6     Bhawna     MBA  89.0


In [48]:
df2['Score'] = pd.to_numeric(df2['Score'], errors='coerce')
print(df2.groupby("Degree")["Score"].max())

Degree
BCA       78.0
M.Tech    80.0
MBA       98.0
NaN       97.0
Name: Score, dtype: float64


In [49]:
df_filled = df2["Score"].fillna(76)
print(df_filled)

0    90.0
1    76.0
2    80.0
3    98.0
4    97.0
5    78.0
6    89.0
Name: Score, dtype: float64


In [50]:
df2.set_index("Name", inplace=True)
print(df2)

           Degree  Score
Name                    
Aparna        MBA   90.0
Pankaj        BCA    NaN
Ram        M.Tech   80.0
Ramesh        MBA   98.0
Naveen        NaN   97.0
Krrishnav     BCA   78.0
Bhawna        MBA   89.0


In [51]:
df2.reset_index(inplace=True)
avg_scores = df2.groupby(["Name", "Degree"])["Score"].mean()
print(avg_scores)


Name       Degree
Aparna     MBA       90.0
Bhawna     MBA       89.0
Krrishnav  BCA       78.0
Naveen     NaN       97.0
Pankaj     BCA        NaN
Ram        M.Tech    80.0
Ramesh     MBA       98.0
Name: Score, dtype: float64


In [52]:
mba_count = df2[df2["Degree"] == "MBA"].shape[0]
print("Number of MBA students:", mba_count)


Number of MBA students: 3


In [53]:
bca_mode = df2[df2["Degree"] == "BCA"]["Score"].mode()
print("Mode of BCA scores:", bca_mode.values)


Mode of BCA scores: [78.]
