<a href="https://colab.research.google.com/github/PochampellyDeekshitha/MachineLearning/blob/main/MachineLearning_Week1%2C2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas Exercise-01**

9th question

In [ ]:
import pandas as pd
sales_data = {
    2014: [100.5, 150.8, 200.9, 30000, 40000],
    2015: [12000, 18000, 22000, 30000, 45000],
    2016: [20000, 50000, 70000, 100000, 125000],
    2017: [50000, 60000, 70000, 80000, 90000]
}
sales= pd.DataFrame(sales_data, index=['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'])
display(sales)

2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000

10th question

In [ ]:
sales.index

Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')

In [ ]:
sales.columns

Index([2014, 2015, 2016, 2017], dtype='int64')

In [ ]:
sales.shape

(5, 4)

In [ ]:
sales.size

20

In [ ]:
sales.ndim

2

In [ ]:
print(sales.values)

[[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]


In [ ]:
sales.tail(2)

2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000

In [ ]:
sales.head(2)

2014   2015   2016   2017
Madhu  100.5  12000  20000  50000
Kusum  150.8  18000  50000  60000

In [ ]:
dict={2018:[160000,110000,500000,340000,900000]}
sales2=pd.DataFrame(dict,index=['Madhu','kusum','kinshuk','ankith','shruthi'])
print(sales2)

           2018
Madhu    160000
kusum    110000
kinshuk  500000
ankith   340000
shruthi  900000


In [ ]:
sales2.empty

False

11th Question

In [ ]:
sales=pd.concat([sales,sales2],axis=1)
print(sales)

            2014     2015      2016     2017      2018
Madhu      100.5  12000.0   20000.0  50000.0  160000.0
Kusum      150.8  18000.0   50000.0  60000.0       NaN
Kinshuk    200.9  22000.0   70000.0  70000.0       NaN
Ankit    30000.0  30000.0  100000.0  80000.0       NaN
Shruti   40000.0  45000.0  125000.0  90000.0       NaN
kusum        NaN      NaN       NaN      NaN  110000.0
kinshuk      NaN      NaN       NaN      NaN  500000.0
ankith       NaN      NaN       NaN      NaN  340000.0
shruthi      NaN      NaN       NaN      NaN  900000.0


In [ ]:
del sales[2018]

In [ ]:
sales=sales.T
print(sales)

        Madhu    Kusum  Kinshuk     Ankit    Shruti  kusum  kinshuk  ankith  \
2014    100.5    150.8    200.9   30000.0   40000.0    NaN      NaN     NaN   
2015  12000.0  18000.0  22000.0   30000.0   45000.0    NaN      NaN     NaN   
2016  20000.0  50000.0  70000.0  100000.0  125000.0    NaN      NaN     NaN   
2017  50000.0  60000.0  70000.0   80000.0   90000.0    NaN      NaN     NaN   

      shruthi  
2014      NaN  
2015      NaN  
2016      NaN  
2017      NaN  


In [ ]:
print(sales.loc[2017])

Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
kusum          NaN
kinshuk        NaN
ankith         NaN
shruthi        NaN
Name: 2017, dtype: float64


In [ ]:
display(sales.loc[[2017], ['Madhu', 'Ankit']])

Madhu    Ankit
2017  50000.0  80000.0

In [ ]:
display(sales.loc[[2016], ['Shruti']])

Shruti
2016  125000.0

In [ ]:
print(sales)

        Madhu    Kusum  Kinshuk     Ankit    Shruti  kusum  kinshuk  ankith  \
2014    100.5    150.8    200.9   30000.0   40000.0    NaN      NaN     NaN   
2015  12000.0  18000.0  22000.0   30000.0   45000.0    NaN      NaN     NaN   
2016  20000.0  50000.0  70000.0  100000.0  125000.0    NaN      NaN     NaN   
2017  50000.0  60000.0  70000.0   80000.0   90000.0    NaN      NaN     NaN   

      shruthi  
2014      NaN  
2015      NaN  
2016      NaN  
2017      NaN  


In [ ]:
sales.loc['Sumeet'] = [196.2, 37800, 52000, 78438, 38852, 0, 0, 0, 0]
print(sales)

          Madhu    Kusum  Kinshuk     Ankit    Shruti  kusum  kinshuk  ankith  \
2014      100.5    150.8    200.9   30000.0   40000.0    NaN      NaN     NaN   
2015    12000.0  18000.0  22000.0   30000.0   45000.0    NaN      NaN     NaN   
2016    20000.0  50000.0  70000.0  100000.0  125000.0    NaN      NaN     NaN   
2017    50000.0  60000.0  70000.0   80000.0   90000.0    NaN      NaN     NaN   
Sumeet    196.2  37800.0  52000.0   78438.0   38852.0    0.0      0.0     0.0   

        shruthi  
2014        NaN  
2015        NaN  
2016        NaN  
2017        NaN  
Sumeet      0.0  


In [ ]:
sales.drop(2014, axis=0, inplace=True)
print(sales)

          Madhu    Kusum  Kinshuk     Ankit    Shruti  kusum  kinshuk  ankith  \
2015    12000.0  18000.0  22000.0   30000.0   45000.0    NaN      NaN     NaN   
2016    20000.0  50000.0  70000.0  100000.0  125000.0    NaN      NaN     NaN   
2017    50000.0  60000.0  70000.0   80000.0   90000.0    NaN      NaN     NaN   
Sumeet    196.2  37800.0  52000.0   78438.0   38852.0    0.0      0.0     0.0   

        shruthi  
2015        NaN  
2016        NaN  
2017        NaN  
Sumeet      0.0  


In [ ]:
sales.drop('Kinshuk', axis=1, inplace=True)
print(sales)

          Madhu    Kusum     Ankit    Shruti  kusum  kinshuk  ankith  shruthi
2015    12000.0  18000.0   30000.0   45000.0    NaN      NaN     NaN      NaN
2016    20000.0  50000.0  100000.0  125000.0    NaN      NaN     NaN      NaN
2017    50000.0  60000.0   80000.0   90000.0    NaN      NaN     NaN      NaN
Sumeet    196.2  37800.0   78438.0   38852.0    0.0      0.0     0.0      0.0


In [ ]:
sales.rename(index={'Madhu':'shailesh','ankith':'vivaan'},inplace=True)
print(sales)

          Madhu    Kusum     Ankit    Shruti  kusum  kinshuk  ankith  shruthi
2015    12000.0  18000.0   30000.0   45000.0    NaN      NaN     NaN      NaN
2016    20000.0  50000.0  100000.0  125000.0    NaN      NaN     NaN      NaN
2017    50000.0  60000.0   80000.0   90000.0    NaN      NaN     NaN      NaN
Sumeet    196.2  37800.0   78438.0   38852.0    0.0      0.0     0.0      0.0


In [ ]:
sales.loc['shailesh',2018]=1000000
print(sales)

            Madhu    Kusum     Ankit    Shruti  kusum  kinshuk  ankith  \
2015      12000.0  18000.0   30000.0   45000.0    NaN      NaN     NaN   
2016      20000.0  50000.0  100000.0  125000.0    NaN      NaN     NaN   
2017      50000.0  60000.0   80000.0   90000.0    NaN      NaN     NaN   
Sumeet      196.2  37800.0   78438.0   38852.0    0.0      0.0     0.0   
shailesh      NaN      NaN       NaN       NaN    NaN      NaN     NaN   

          shruthi       2018  
2015          NaN        NaN  
2016          NaN        NaN  
2017          NaN        NaN  
Sumeet        0.0        NaN  
shailesh      NaN  1000000.0  


In [ ]:
sales.to_csv('SalesFigures.csv', index=False, header=False)

In [ ]:
SalesRetrieved = pd.read_csv('SalesFigures.csv', header=None)
SalesRetrieved.index = sales.index
SalesRetrieved.columns = sales.columns
print(SalesRetrieved)

            Madhu    Kusum     Ankit    Shruti  kusum  kinshuk  ankith  \
2015      12000.0  18000.0   30000.0   45000.0    NaN      NaN     NaN   
2016      20000.0  50000.0  100000.0  125000.0    NaN      NaN     NaN   
2017      50000.0  60000.0   80000.0   90000.0    NaN      NaN     NaN   
Sumeet      196.2  37800.0   78438.0   38852.0    0.0      0.0     0.0   
shailesh      NaN      NaN       NaN       NaN    NaN      NaN     NaN   

          shruthi       2018  
2015          NaN        NaN  
2016          NaN        NaN  
2017          NaN        NaN  
Sumeet        0.0        NaN  
shailesh      NaN  1000000.0  


**Pandas Exrecise-02**

13th question

In [ ]:
import pandas as pd
data = {"Item": ["TV", "TV", "TV", "AC"],"Company": ["LG", "VIDEOCON", "LG", "SONY"],"Rupees": [12000, 10000, 15000, 14000],"USD": [700,650,800,750]}
df = pd.DataFrame(data)
print(df)

  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750


In [ ]:
new_data = pd.DataFrame([
{"Item": "TV", "Company": "SAMSUNG", "Rupees": 13000, "USD": 670},
{"Item": "AC", "Company": "Apple", "Rupees": 16000, "USD": 900}
])
df = pd.concat([df, new_data], ignore_index=True)
print(df)


  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
4   TV   SAMSUNG   13000  670
5   AC     Apple   16000  900


In [ ]:
lg_tv_max = df[(df['Item'] == 'TV') & (df['Company'] == 'LG')]['Rupees'].max()
print("Maximum price of LG TV:", lg_tv_max)

Maximum price of LG TV: 15000


In [ ]:
total_rupees = df['Rupees'].sum()
print("Total sum of all products in Rupees:", total_rupees)

Total sum of all products in Rupees: 80000


In [ ]:
sony_median_usd = df[df['Company'] == 'SONY']['USD'].median()
print("Median USD for SONY products:", sony_median_usd)

Median USD for SONY products: 750.0


In [ ]:
sorted_df = df.sort_values(by='Rupees')
print(sorted_df)

  Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
4   TV   SAMSUNG   13000  670
3   AC      SONY   14000  750
2   TV        LG   15000  800
5   AC     Apple   16000  900


In [ ]:
sorted_df = df.sort_values(by='Rupees')
print(sorted_df)


  Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
4   TV   SAMSUNG   13000  670
3   AC      SONY   14000  750
2   TV        LG   15000  800
5   AC     Apple   16000  900


14th question

In [ ]:
import numpy as np
data = {"Name": ["Aparna", "Pankaj", "Ram", "Ramesh", "Naveen", "Krrishnav", "Bhawna"],"Degree": ["MBA", "BCA", "M.Tech", "MBA", "NaN","BCA","MBA"],"Score":[90.0,"NaN",80.0,98.0,97.0,78.0,89.0]}
df2 = pd.DataFrame(data)
print(df2)


        Name  Degree Score
0     Aparna     MBA  90.0
1     Pankaj     BCA   NaN
2        Ram  M.Tech  80.0
3     Ramesh     MBA  98.0
4     Naveen     NaN  97.0
5  Krrishnav     BCA  78.0
6     Bhawna     MBA  89.0


In [ ]:
df2['Score'] = pd.to_numeric(df2['Score'], errors='coerce')
print(df2.groupby("Degree")["Score"].max())

Degree
BCA       78.0
M.Tech    80.0
MBA       98.0
NaN       97.0
Name: Score, dtype: float64


In [ ]:
df_filled = df2["Score"].fillna(76)
print(df_filled)

0    90.0
1    76.0
2    80.0
3    98.0
4    97.0
5    78.0
6    89.0
Name: Score, dtype: float64


In [ ]:
df2.set_index("Name", inplace=True)
print(df2)

           Degree  Score
Name                    
Aparna        MBA   90.0
Pankaj        BCA    NaN
Ram        M.Tech   80.0
Ramesh        MBA   98.0
Naveen        NaN   97.0
Krrishnav     BCA   78.0
Bhawna        MBA   89.0


In [ ]:
df2.reset_index(inplace=True)
avg_scores = df2.groupby(["Name", "Degree"])["Score"].mean()
print(avg_scores)


Name       Degree
Aparna     MBA       90.0
Bhawna     MBA       89.0
Krrishnav  BCA       78.0
Naveen     NaN       97.0
Pankaj     BCA        NaN
Ram        M.Tech    80.0
Ramesh     MBA       98.0
Name: Score, dtype: float64


In [ ]:
mba_count = df2[df2["Degree"] == "MBA"].shape[0]
print("Number of MBA students:", mba_count)


Number of MBA students: 3


In [ ]:
bca_mode = df2[df2["Degree"] == "BCA"]["Score"].mode()
print("Mode of BCA scores:", bca_mode.values)


Mode of BCA scores: [78.]


In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold

In [5]:
df=pd.read_csv('favorite_music_dataset.csv')
print(df.ndim)    #output 1 for series 2 for dataframe
print(df.shape)   #no.of rows and columns
print(df.size)    #rows*columns

2
(100, 7)
700


In [6]:
print(df.head(10))

          Song_Title       Artist       Genre  Release_Year  Duration_Minutes  \
0              Faded  Alan Walker  Electronic          2024              4.02   
1    Blinding Lights   The Weeknd   Synth-pop          2018              4.45   
2              Faded  Alan Walker  Electronic          2024              4.86   
3              Faded  Alan Walker  Electronic          2012              4.92   
4  Bohemian Rhapsody        Queen        Rock          2023              3.90   
5            Perfect   Ed Sheeran  Pop Ballad          2014              4.65   
6         Let Her Go    Passenger       Indie          2020              3.39   
7    Blinding Lights   The Weeknd   Synth-pop          2011              2.67   
8         Let Her Go    Passenger       Indie          2016              4.05   
9  Bohemian Rhapsody        Queen        Rock          2015              3.98   

  Listened_Date     Platform  
0    2024-02-10  Apple Music  
1    2024-05-30     Zing MP3  
2    2024-05-07

In [7]:
print(df.tail(5))

         Song_Title                         Artist      Genre  Release_Year  \
95   Counting Stars                    OneRepublic   Pop Rock          2013   
96         Senorita  Shawn Mendes & Camila Cabello  Latin Pop          2024   
97   Counting Stars                    OneRepublic   Pop Rock          2010   
98  Blinding Lights                     The Weeknd  Synth-pop          2012   
99       Let Her Go                      Passenger      Indie          2013   

    Duration_Minutes Listened_Date     Platform  
95              3.40    2024-05-30      Spotify  
96              2.75    2024-06-11  Apple Music  
97              3.57    2024-01-03     Zing MP3  
98              4.04    2024-06-13  Apple Music  
99              4.61    2024-01-04  Apple Music  


In [8]:
[col for col in df.columns if df[col].isnull().sum()>0]     #checks if null values present or not

[]

In [12]:
x_train,x_test,y_train,y_test=train_test_split(
    df.drop(labels=['Platform'],axis=1),      #axis=1 is column
    df['Platform'],
    test_size=0.3,
    random_state=0
)

In [13]:
constant_features=[
    features for features in x_train.columns if x_train[features].std==0
]
len(constant_features)


0

In [14]:
print(constant_features)

[]


In [15]:
# Add a specific column to the constant_features list
constant_features.append('Artist')

# Print the updated list
print(constant_features)

['Artist']


In [16]:
x_train.drop(labels=constant_features,axis=1,inplace=True)
x_test.drop(labels=constant_features,axis=1,inplace=True)

In [ ]:
import pandas as pd
import numpy as np

# WEEK-**2**

In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold

In [ ]:
df=pd.read_csv("/content/games.csv")
df.shape

(20058, 16)

In [ ]:
df

id  rated    created_at  last_move_at  turns victory_status  \
0      TZJHLljE  False  1.504210e+12  1.504210e+12     13      outoftime   
1      l1NXvwaE   True  1.504130e+12  1.504130e+12     16         resign   
2      mIICvQHh   True  1.504130e+12  1.504130e+12     61           mate   
3      kWKvrqYL   True  1.504110e+12  1.504110e+12     61           mate   
4      9tXo1AUZ   True  1.504030e+12  1.504030e+12     95           mate   
...         ...    ...           ...           ...    ...            ...   
20053  EfqH7VVH   True  1.499791e+12  1.499791e+12     24         resign   
20054  WSJDhbPl   True  1.499698e+12  1.499699e+12     82           mate   
20055  yrAas0Kj   True  1.499698e+12  1.499698e+12     35           mate   
20056  b0v4tRyF   True  1.499696e+12  1.499697e+12    109         resign   
20057  N8G2JHGG   True  1.499643e+12  1.499644e+12     78           mate   

      winner increment_code       white_id  white_rating            black_id  \
0      white           15+2       bourgris          1500                a-00   
1      black           5+10           a-00          1322           skinnerua   
2      white           5+10         ischia          1496                a-00   
3      white           20+0  daniamurashov          1439        adivanov2009   
4      white           30+3      nik221107          1523        adivanov2009   
...      ...            ...            ...           ...                 ...   
20053  white          10+10        belcolt          1691            jamboger   
20054  black           10+0       jamboger          1233  farrukhasomiddinov   
20055  white           10+0       jamboger          1219        schaaksmurf3   
20056  white           10+0   marcodisogno          1360            jamboger   
20057  black           10+0       jamboger          1235               ffbob   

       black_rating                                              moves  \
0              1191  d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...   
1              1261  d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...   
2              1500  e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...   
3              1454  d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...   
4              1469  e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...   
...             ...                                                ...   
20053          1220  d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...   
20054          1196  d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...   
20055          1286  d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...   
20056          1227  e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...   
20057          1339  d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...   

      opening_eco                            opening_name  opening_ply  
0             D10        Slav Defense: Exchange Variation            5  
1             B00  Nimzowitsch Defense: Kennedy Variation            4  
2             C20   King's Pawn Game: Leonardis Variation            3  
3             D02  Queen's Pawn Game: Zukertort Variation            3  
4             C41                        Philidor Defense            5  
...           ...                                     ...          ...  
20053         A80                           Dutch Defense            2  
20054         A41                            Queen's Pawn            2  
20055         D00         Queen's Pawn Game: Mason Attack            3  
20056         B07                            Pirc Defense            4  
20057         D00         Queen's Pawn Game: Mason Attack            3  

[20058 rows x 16 columns]

In [ ]:
df['black_rating'].value_counts()

black_rating
1500    797
1400     69
1501     53
1810     49
1562     45
       ... 
2468      1
2524      1
1059      1
864       1
2289      1
Name: count, Length: 1521, dtype: int64

In [ ]:
[col for col in df.columns if df[col].isnull().sum()>0]

[]

In [ ]:
df[df['black_id'].isnull()]

Empty DataFrame
Columns: [id, rated, created_at, last_move_at, turns, victory_status, winner, increment_code, white_id, white_rating, black_id, black_rating, moves, opening_eco, opening_name, opening_ply]
Index: []

In [ ]:
df.columns

Index(['id', 'rated', 'created_at', 'last_move_at', 'turns', 'victory_status',
       'winner', 'increment_code', 'white_id', 'white_rating', 'black_id',
       'black_rating', 'moves', 'opening_eco', 'opening_name', 'opening_ply'],
      dtype='object')

In [ ]:
df = df.dropna(subset=['opening_ply'])

In [ ]:
[col for col in df.columns if df[col].isnull().sum()>0]

[]

In [ ]:
X= df.drop(labels=['opening_ply'],axis=1)
y=df['opening_ply']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
# constant features
constant_features=[features for features in x_train.columns if x_train[features].std()==0]
print(constant_features)

TypeError: could not convert string to float: 'E2ODizgR'

In [ ]:
X=pd.get_dummies(X,drop_first=True)

In [ ]:
X.shape

(20058, 59048)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
constant_features=[features for features in x_train.columns if x_train[features].std()==0]
len(constant_features)

0

In [ ]:
x_train.drop(labels=constant_features,axis=1,inplace=True)
x_test.drop(labels=constant_features,axis=1,inplace=True)

In [ ]:
# quasi constant features
quasi_constant_feat=[]
for feature in x_train.columns:
  predominant=(x_train[feature].value_counts()/float(len(x_train))).sort_values(ascending=False).values[0]
  if predominant>0.999:
    quasi_constant_feat.append(feature)
len(quasi_constant_feat)

42600

In [ ]:
# duplicated features
dup=[]
for i in range (0,len(x_train.columns)):
    col1=x_train.columns[i]
    for col2 in x_train.columns[i+1:]:
        if x_train[col1].equals(x_train[col2]):
            dup.append(col2)
dup_features=set(dup)
print(len(dup_features))

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
corrmat=x_train.corr()
fig,ax=plt.subplots()
fig.set_size_inches(5,5)
sns.heatmap(corrmat)

In [ ]:
corrmat=x_train.corr()
fig,ax=plt.subplots()
fig.set_size_inches(16,16)
sns.heatmap(corrmat)

In [ ]:
grouped_feature_ls = []
correlated_groups = []
def correlation (dataset, threshold):
    col_corr = set() # Set of all the names of correlated columns
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold: # we are interested in absolute coeff value
                colname=corr_matrix.columns[i] #3 getting the name of column
                col_corr.add(colname)
    return col_corr
corr_features=correlation (x_test, 0.9) # filter for all the features with corre lation more than 0.9
correlated_features = set(corr_features) # Set statement is used to identify the unique feature in the list
print(len(correlated_features)) # length of set of correlated features

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_selection import mutual_info_classif, SelectKBest

# Step 1: Calculate Mutual Information scores
mi = mutual_info_classif(x_train.fillna(0), y_train)
mi = pd.Series(mi, index=x_train.columns)

# Step 2: Visualize MI scores
mi.sort_values(ascending=False).plot.bar(figsize=(20, 4))
plt.title("Mutual Information Scores")
plt.ylabel("MI Score")
plt.xlabel("Features")
plt.show()

# Step 3: Select top 10 features based on MI
selector = SelectKBest(score_func=mutual_info_classif, k=10)
selector.fit(x_train.fillna(0), y_train)

# Step 4: Get selected feature names
selected_features = x_train.columns[selector.get_support()]
print("Top 10 Selected Features:\n", selected_features.tolist())